---
# tasks file for win_ad_install
  - name: Install AD-Domain-Services feature
    win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes

  - name: Setup AD Controller
    win_domain:
      dns_domain_name: "{{ ad_domain_name }}"
      safe_mode_password: "{{ ad_safe_mode_password }}"
    register: active_directory_controller

  - name: Reboot AD Instance after DC completion
    win_reboot:
      when: active_directory_controller.reboot_required

  - name: Print domain list after reboot
    win_shell: "nltest /dclist:{{ ad_domain_name }}"
    register: domain_list

  - debug:
      var: domain_list

